### ISSUE TITLE
As of this build No World Quest Tooltips

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#540] opened 2016-10-05 16:39 UTC
Just noticed, and I apologize for not checking this morning, no tooltips on map for world quests.

**Comment by IrcDirk** [comment] 2016-10-05 16:51
On maximized works no problem, maybe on minimized it doesnt work?

**Comment by SteveEbey73742** [comment] 2016-10-05 17:24
actuallly, on mini map, it showed up once, then used map maximized, and no tips.  I will post screen shot later.  Need to go fix a computer for a person.

**Comment by IrcDirk** [comment] 2016-10-05 19:45
Ok u got "Close map instead of minimize"... thats the case i didnt took into consideration... will make fix for this.

**Comment by SteveEbey73742** [comment] 2016-10-05 21:52
updated my fork, installing. will test and report back.

**Comment by samyonair** [comment] 2016-10-06 08:39
Just tested it works, minor Issue only Yesterday one Time I used m-Key to maximize but Map do not maximize instead show buttons for the Daily Worldquest (Do 4 Quests for faction) and another strokes on Key only activated / deactivated it, after Closening Map it was gone and function was back, cannot reproduce why.

Greetings

**Comment by IrcDirk** [comment] 2016-10-06 09:03
Yes @samyonair i got this sometimes too... dont know why, trying to debug with no luck ;)

**Comment by Morindra** [comment] 2016-10-09 02:38
alt-L map, click back to look at all of broken isles, click specific area to see world quests.  The information is showing up BEHIND the quest window.

**Comment by IrcDirk** [comment] 2016-10-10 08:33
using M key then Alt-M moves all things were there should be, need to fix those other cases.

**Comment by Morindra** [comment] 2016-10-10 23:39
My issue of it popping up behind the map is resolved.

**Closed** 2016-10-20 11:29 UTC
Labels: fixed please confirm, Quests
