### ISSUE TITLE
Minimap off-center

### ISSUE THREAD

**Issue by Ghosthree3** [mikepauer/Carbonite#219] opened 2015-01-03 10:22 UTC
Using the release version on Curse, not sure if you've fixed it since then. Posted it in the thread on wowinterface, but it didn't get fixed between then and release.

Original post here, http://www.wowinterface.com/forums/showthread.php?p=302734#post302734

The first image is the regular minimap, the second is the minimap while holding ctrl - shows what the normal blizz mini map would show when you do that? - the first is incorrect, the second is where I actually am.

http://i.imgur.com/i17LXb7.png
http://i.imgur.com/GBnPgiE.png

You can see how the circle area shifts significantly if you look at where the pool of water crosses in and out of the circle.

**Comment by atk** [comment] 2015-01-05 08:22
I can confirm that position/scaling seem indeed a bit off.

**Comment by IrcDirk** [comment] 2015-01-05 10:46
I confirm that too. Slighty off.

**Comment by atk** [comment] 2015-01-05 11:09
I have already tried to play around with the values in NxMapData.lua on line 1271, but since I didn't know what I'm doing, I haven't yet found the right values.

**Comment by IrcDirk** [comment] 2015-01-05 11:17
Not only one map is off, some others too. I think all WoD maps are a little bit off.

**Comment by Ghosthree3** [comment] 2015-01-05 11:57
Is it just WoD maps, or all maps?

**Comment by IrcDirk** [comment] 2015-01-05 12:24
Tested:
* Kalimdor -> Durotar and its off too.

**Comment by DaveJ61** [comment] 2015-01-05 13:04
I've had quite a few issues with maps and waypoints/flight point's etc and I don't know whether this is connected.
Just to highlight this I have included some screenshots:-
![wowscrnshot_010515_065234](https://cloud.githubusercontent.com/assets/1816367/5613345/e2c9d3f2-94da-11e4-9c72-2c402e7a52da.jpg)
![wowscrnshot_010515_065242](https://cloud.githubusercontent.com/assets/1816367/5613346/e86744ac-94da-11e4-8a88-5f2912107cd2.jpg)
![wowscrnshot_010515_065257](https://cloud.githubusercontent.com/assets/1816367/5613348/ee185ec2-94da-11e4-8c1c-3d8c12a33716.jpg)
![wowscrnshot_010515_065315](https://cloud.githubusercontent.com/assets/1816367/5613351/f21c5a32-94da-11e4-8682-ec45c19a0af9.jpg)
and this last one appears to be correct.:-
![wowscrnshot_010515_065322](https://cloud.githubusercontent.com/assets/1816367/5613358/0300ec28-94db-11e4-95a1-b697d1d65dc4.jpg)

This appears to vary depending on where on the map your mouse pointer is located.

**Comment by IrcDirk** [comment] 2015-01-05 13:10
Are u using Live or GitHub version of Carbonite?

**Comment by DaveJ61** [comment] 2015-01-05 13:15
Github...

**Comment by IrcDirk** [comment] 2015-01-05 13:39
Im having latest version from GitHub, this works fine, cant recreate. Maybe other addon? Disable all and check with only Carbonite enabled.

**Comment by DaveJ61** [comment] 2015-01-05 21:29
I now have just Carbonite loaded and still getting the same thing. I think it possibly has something to do with unexplored areas and also the moving the mouse cursor over an unexplored area or another zone like Talador changes everything as can be seen by these two screenshots. There also appears to be something weird happening with unexplored areas anyway.:-
![wowscrnshot_010515_212342](https://cloud.githubusercontent.com/assets/1816367/5620205/947aaa40-9521-11e4-994c-ef4026be7994.jpg)
![wowscrnshot_010515_212354](https://cloud.githubusercontent.com/assets/1816367/5620208/9dccaf76-9521-11e4-8284-592901317904.jpg)

**Comment by IrcDirk** [comment] 2015-01-06 03:48
Good job! I think u have right, the unexplored areas are the problem. We should do separate issue for that.

**Comment by deathcore01** [comment] 2015-01-07 18:39
i think not the unexplored areas are the problem! i have found one bug more: set the option "Center map when maximizing" of off and hit m to toggle map, the error with "centery is a nil value" is back. i think this is a problem with the Nx.Map:AttachWorldMap() function (NxMap.lua, line 1381). i have commented out the call self:AttachWorldMap() into function Nx.Map:OnWin (typ) (line 1371 by me) and have no error anymore. the problem above here in the pictures are non present if AttachWorldMap() is not called. i think here is the begin of serch the error...

**Comment by DaveJ61** [comment] 2015-01-07 18:49
I have also seen negative location coordinates too. Yesterday I was trying to pinpoint a location on the map and the coordinates kept stopping to update and freezing. In the end I had to give up as it wasn't working.

**Comment by IrcDirk** [comment] 2016-08-13 10:29
It should be fixed. Please confirm.

**Comment by JWMcQuire** [comment] 2016-08-23 16:22
I just took a flight from Southport to Veil Terokk, and it looks like this issue as illustrated in Dave's second screenshot has been fixed. However I had to log off because of a server restart, so further confirmation from someone else may be helpful.

**Closed** 2016-09-28 06:08 UTC
Labels: bug, fixed please confirm, Main Addon
