### ISSUE TITLE
Make Handynotes work with instance maps

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#658] opened 2017-05-09 17:26 UTC
I know you dont like the whole instance maps thing, because blizzard literally destroyed them. But it would be very nice to get Handynotes work on them.

Should be looking like this:
![wow5](https://cloud.githubusercontent.com/assets/22813377/25863704/1c50e624-34ed-11e7-99e4-733ae9d718cf.PNG)

Looks like this:
![wowscrnshot_050917_192335](https://cloud.githubusercontent.com/assets/22813377/25863763/56912d26-34ed-11e7-8737-d837e951a5fb.jpg)

**Comment by IrcDirk** [comment] 2017-05-09 17:51
Which handynotes are this? Some special for Legion?  Have handynotes and i dont see those on Blizz map.

**Comment by jeffy162** [comment] 2017-05-09 18:02
Yeah, this used to happen with Minimap Button Frame, also. The dev's have to find out what causes this, and then code for it. It's probably picking up those icons ON the map as minimap buttons (which should be on the perimeter of the minimap) instead of the "minimap icons" that they are.

I know that it's an easy fix, but, I don't know what that fix is, unfortunately.

**Comment by fdellwing** [comment] 2017-05-09 18:40
https://mods.curse.com/addons/wow/265431-handynotes-legion-class-order-halls

That module.

**Comment by IrcDirk** [comment] 2017-05-12 06:51
This addon should work in DH order class hall. It should show icons but there is problem with their code, they dont return icon level and DH order class hall has 3 levels. Becouse of that Carbonite doesnt know where to put those icons so it ignores them. 

**Addon authors should fix their _PluginHandler:GetNodes_ function to return correct icon level.**

**Comment by fdellwing** [comment] 2017-05-12 06:53
Well, but it works on BlizzMap?

**Comment by IrcDirk** [comment] 2017-05-12 06:54
It works becouse HandyNotes puts icons on actual opened map, so it doesnt need instance level.

**Comment by arithmandar** [comment] 2017-05-12 09:39
Hey IrcDirk, I am the author of HandyNotes - Legion Class Order Hall. 
Just did a quick code change, to allow iter function to return dungeonLevel value, but it doesn't seem to make any different in Carbonite map.

**Comment by IrcDirk** [comment] 2017-05-12 09:41
Thanks... i need to make one change to make it work now.

**Comment by IrcDirk** [comment] 2017-05-12 12:16
Ohh... but u didnt update it? I cant see changes on curse :(

**Comment by fdellwing** [comment] 2017-05-12 12:18
There was an update on Curse 3hours ago.

**Comment by IrcDirk** [comment] 2017-05-12 12:22
Ohh i see on project site https://wow.curseforge.com/projects/handynotes-legion-class-order-halls not on curse main addon site.

**Comment by fdellwing** [comment] 2017-05-12 12:23
Curseforge is live linked with Curse, so that can not be.

And I see the change on the main addon site.

**Comment by IrcDirk** [comment] 2017-05-12 12:26
Its not a release so Curse app will not update it ;) Thats my problem. But i did update it by hand.

**Comment by fdellwing** [comment] 2017-05-12 12:28
Ah I see, its tagged as alpha version. On the curse site I cannot see that, there it just states a change 3h ago. Strange...

**Comment by arithmandar** [comment] 2017-05-12 12:40
It's should be available in the latest alpha build. I will tag it as a release right after I have tested it with Carbonite.

**Comment by mikepauer** [comment] 2017-05-12 12:41
Your changes to start including dungeon level worked as far as I can tell, the problem is on carbonites side, and a revamp of the map icons system needed. 

Currently everything converts a map location (mapid,x,y) into a global world location (using GetWorldPos) that only Carbonite understands and uses. With the new instance maps those numbers are useless since it needs to go back to using mapid,x,y.

The easiest solution at least in my thoughts right now is to change AddIconPt so it takes mapid,x,y instead of mapid,wx,xy and then when drawing the icon convert to wx,xy if it's needed, don't convert it if it's an instance map and doesn't need it.

**Comment by IrcDirk** [comment] 2017-05-12 12:58
@mikepauer im on it ;) will post fix in few hours.

**Comment by fdellwing** [comment] 2017-05-13 06:26
Works with "Show Instance Map". Did not check for any strange Interactions.

**Comment by IrcDirk** [comment] 2017-05-13 17:14
@arithmandar i did posted u an issue https://wow.curseforge.com/projects/handynotes-legion-class-order-halls/issues/2

**Comment by Thrumbar** [comment] 2017-05-14 00:55
Not able to find MapId for Sanctum of Light...  This may be the issue as in Carbonite I most the time show Eastern Plaguelands while in Sanctum of Light....

**Comment by IrcDirk** [comment] 2017-05-14 07:58
Sanctum of Light is microdungeon ... GetMapInfo u will have mapid for eastern and info about microdungeon. 

Bug is in HandyNotes it self or in @arithmandar plugin. I have tested it with all addons disabled (Carbonite disabled too) only HandyNotes and HandyNotes - Legion Class Order Hall enabled and it doesnt show icons.

**Comment by IrcDirk** [comment] 2017-05-15 09:48
@arithmandar made fix for HandyNotes - Legion Class Order Hall and i did fixed HandyNotes in MicroDungeons. Now in Sanctum of Light icons are shown.

**Comment by arithmandar** [comment] 2017-05-15 11:12
Looks like Rogue's class hall may need some more code changes as the map itself didn't show properly.
I also tested Priest's class hall, icons from HandyNotes - Class Order Halls are not showing.

**Comment by IrcDirk** [comment] 2017-05-15 11:15
With todays commit?

**Comment by arithmandar** [comment] 2017-05-15 11:27
That's right. I have tested all classes, looks like only Rogue and Priest have problems, but different issues.

**Comment by IrcDirk** [comment] 2017-05-15 18:46
@arithmandar Should be fixed now.

**Comment by arithmandar** [comment] 2017-05-16 08:34
Looks good now.

**Comment by IrcDirk** [comment] 2017-05-16 09:54
@arithmandar u tried all others orders halls?

**Comment by arithmandar** [comment] 2017-05-16 10:36
Just tested again in all classes' order halls. Icons from HandyNotes Class Order Halls can be shown on the Carbonite maps. Except Rogue's order hall, it seems to have problem in showing expected map. 

While in Paladin or DK's order hall, it seems to be taking a little bit longer to wait for the expected map to be shown.

**Comment by IrcDirk** [comment] 2017-05-16 10:39
Know about those issues with maps.

So it seems issues with HandyNotes are fixes. Closing. 

**To all: Big thanks for cooperation!**

**Closed** 2017-05-16 10:40 UTC
Labels: Carbonite.Notes, fixed please confirm
