### ISSUE TITLE
Quest complete sound not working

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#417] opened 2016-07-23 15:41 UTC
Hi,
Just lately I have had this issue where the quest complete sound is not working. I can't remember when it stopped working but it was a few days ago and I have been too busy to investigate it, until now.
There is no sound at all. I have tried all the other alternatives, such as the peon 'work complete' but still not working.
The sound plays when you select the sound in the quest module, however, it does not sound on quest completion.

**Comment by DaveJ61** [comment] 2016-07-23 16:16
Just turned a quest in just inside Sethek halls. I had already complete the quest 'Can't stay away' a little while ago. Anyway, on exiting the instance, it then decided to give me a sound to say the quest was complete!!?

**Comment by DaveJ61** [comment] 2016-07-23 17:10
Cancel, please... Just discovered that another addon, Glamour seemed to be conflicting. All working fine now... thanks

**Comment by DaveJ61** [comment] 2016-08-08 00:16
Hi,

After further investigation, this issue is still a problem. I am also witnessing some strange anomalies.
I thought it was a particular addon called glamour, which I have completely disabled anyway. I also had another addon called Elphies Interruptsay, which just announces that I interrupted a spell to the party or raid. I didsabled this as well. I then installed an uptodate addon that does the same thing called Interrupt Announcer.
I can't help thinking that there is some mechanism somewhere common to these addons that interfere with the operation of Carbonite's quest complete announcement. It is not any particular addon.
I can actually test the sounds in the quest sound module without any problem.
Also, a really weird thing is I recently completed a quest in Tanaris but before turning it in, I hearthed out to Brackenwall Village (forgot to change this, lol), and upon materialising I get a "Quest complete!" notification.

**Comment by DaveJ61** [comment] 2016-08-10 21:01
I managed to get this working but now it has stopped again after an update earlier this morning. There is something flakey about this as it seems to come and go.

**Comment by Rythal** [comment] 2016-08-13 02:15
For me it's working :/ I'll keep watch tho to see if it cuts out

**Comment by DaveJ61** [comment] 2016-08-15 00:48
I am currently checking this and the only addon I have loaded is Carbonite and it is still not working.

![qccapture](https://cloud.githubusercontent.com/assets/1816367/17653252/49871a5e-628a-11e6-848a-f7b5ae406736.JPG)

**Comment by JWMcQuire** [comment] 2016-08-15 03:04
I tried to repeat this problem, and the only way I could get Carbonite to stop playing the quest complete sound without disabling it in Carbonite was to disable sound effects in the game.

So maybe check to see if your sound effects are disabled or turned down all the way in the Blizzard's system settings.

Oh, wait. I didn't test this yet, but also in Blizzard's System settings, make sure your sound output is set for your sound card instead of "System Default".

**Comment by DaveJ61** [comment] 2016-08-15 07:59
Hi,

The in-game sound effects are on and always are. One thing I did see was that the ouput device was selected as my Asus screen but the sound was actually coming from my 5.1 speakers. That in itself is a bit strange. So I selected my speakers but that has made no difference. I cannot see anything external to wow which could cause this. There are no other sound issues with wow or anything else on the machine so I haven't a clue what could be wrong. The fact that I can manually play the sounds in the config seems to suggest that there is something preventing Carbonite from detecting a quest completion. However, I will test later when I get back from work, but I reset all wow settings to default and I think it might be fixed.

**Comment by DaveJ61** [comment] 2016-08-16 18:27
I've been testing this further and it really is quite strange. I kept re-enabling addons and testing and then I installed Pawn and it stopped working. However, uninstalling Pawn did not bring the 'Quest complete' back. I had to uninstall everything apart from Carbonite and relog.

To be honest I am lost and not sure how I can diagnose this any further. I might add a line into the code at the point that the sound is made. Something that would output text to the chat window for debugging purposes.

**Comment by JWMcQuire** [comment] 2016-08-16 21:59
Here are some more suggestions that will either help fix your issue or not. In any case, I hope it at least gives you some ideas for getting this issue fixed. Here is what I can offer.

Try installing one or both of these two addons. I installed them so I could add my own sound files for addons that allow for multiple sound choices for addons. I don't know if it will help you get back the quest finished sound, but maybe it's worth a try.

The first one is "LibSharedMedia-3.0", last updated 6/23/2015 by Elkano. The brief description on curse states, "Shared handling of media data (fonts, sounds, textures...) between addons.

The other one is "SharedMedia", last updated 7/23/2016 by Elkano and Seerah.

Here are a couple of other suggestions:

Clear your cache by deleting the "Cache" folder in the main WoW folder.
Delete or rename the "WTF" folder so WoW will recreate it. This will reset your addon settings and I think your game settings as well, so for me it is a "last ditch effort" for fixing addon related issues.

Short of deleting the whole "WTF" folder, you can go into:

... WTF\Account\(number-ex: 58621675#3)\SavedVariables

and look for addon remnants that you no longer have installed. As good as Curse Client is at adding and removing addons, it doesn't clean the SavedVariables folder very well, so it gathers a lot of junk over time from adding and deleting addons. If Pawn was the beginning of this issue some of it's remnants if any exist may be part of your problem(...but that is only a theory at best).

Another option that may fix your issue is to just delete the Carbonite.lua file in your SavedVariables folder which will reset it back to its original default settings. Then go from there to see if that fixes your issue. I would probably try this first.

I hope this helps or you find a way to get this fixed if not.

**Comment by DaveJ61** [comment] 2016-08-18 18:37
Ok. I was getting so fed up that this isn't working, I went the whole distance and installed a fresh copy of WOW. Installed just carbonite and still nothing. All other programs work flawlessly. "Quest complete" sounds ok in the configuration but not when a quest is completed. I even witnessed one event where I hearthed out to another zone and then I got I finally got the "Quest complete" sound, albeit way too late. I have disabled the settings, re-enabled them, tried different sounds, and even selected all of them. Still nothing. I installed a seperate questcomplete addon, which works fine, so why not carbonite. I am thinking now that the sounds are fine, it is just that they are not being triggered.

I have exhausted everything as I have completely reinstalled everything from scratch and only have carbonite installed. I have previously tried installing the libsharedmedia addon but that didn't work and I shouldn't have to use that to make it work. It was not pawn that caused this as previously mentioned. That was just a coincidence.

Any ideas what next because at the moment it is just pointing to carbonite.

**Comment by DaveJ61** [comment] 2016-08-18 19:01
An update.... I posted the above as soon as I got back from work. When I left this morning, the above was the current status. Now, I have just logged into the game again after doing absolutely nothing and it appears to be working again. However, I have witnessed this before where it works fine for a while and then stops again. I am wondering whether this is a blizzard feature.

**Comment by DaveJ61** [comment] 2016-08-19 11:28
I thought I would try using another character and sure enough my priest and warlock are working absolutely fine. Checked back with he shaman and nada, nothing. Created another shaman but this works fine so it had to be something to do with this particular character but they all have the same addons and pretty much the same settings as far as I can tell. Checked back with the warlock and priest and both still ok. Tried the shaman again and hey presto!, its working but only lasted for one quest and then packed up again. I'm lost now as I haven't a clue what could be causing as I have just about exhausted everything I can think of.

**Comment by DaveJ61** [comment] 2016-08-22 07:31
I can't consistently get this to work and I have even tried on several other characters on different realms which I haven't touched for months. Same addons, and nothing. I have tried everything I can think of, but in the meantime I have installed another addon called PeonQuestComplete, which works every time. This is out of date (30/10/14) but it still works without error.

**Comment by SteveEbey73742** [comment] 2016-08-22 23:31
I am experiencing the same issue, with sound being there for some quests, like the older content, but not for others.  I can get the quest complete to play in Draenor, for the dailies in the jungle and around the garrison, but not in any pre patch content.  Probably unrelated, but the Windows 10 anniversary update killed all sound in WoW, until I went to the setting on my soundblaster and disabled the enhanced features.  I have had Windows 10 installed since the initial free release, and up to now, no issues with it in any games, but the anniversary update screwed the pooch when it got put on.

**Comment by Rythal** [comment] 2016-08-23 03:17
Need a lot more details...

What was the quest?
Did you see in the chat "[Carbonite] Quest complete"?
Is it a daily? event? 
Did watcher/quest log show it as complete?

**Comment by DaveJ61** [comment] 2016-08-23 06:26
Ok, more info, although I have given a load of it. Here is some more with screen shots:

I had to go back to a lower area to do some herb farming and when I hearthed back to Dreadmaul Hold in Blasted Lands, the pc bellowed "Quest Complete". I looked in the chat window and saw this:-
![carb3](https://cloud.githubusercontent.com/assets/1816367/17882046/f4970cf6-6901-11e6-9cdc-17fcad0b3b17.JPG)

I had already completed these two quests and turned them in back in Felwood. Please note that it does NOT say "[Carbonite] Quest complete".
![carb1](https://cloud.githubusercontent.com/assets/1816367/17881914/df0cb008-6900-11e6-8f97-f834ccd4f185.JPG)

Also, is it support to also say "[Carbonite] quest accepted"? This does not:-
![carb2](https://cloud.githubusercontent.com/assets/1816367/17881982/7247b7dc-6901-11e6-8774-00547f272f20.JPG)

After this I went through the Dark Portal and on emerging on the other side I was greeted with "Quest Complete!". This quest I had also completed a while ago but as yet have not turned it in:-
![carb4](https://cloud.githubusercontent.com/assets/1816367/17882125/689b259c-6902-11e6-9a83-3efbe599ae8d.JPG)

These are not dailies. They are regular quests.
I'm not sure what the watcher/quest log is or where to find it.

**Comment by jeffy162** [comment] 2016-08-23 11:47
The Quest Watch is the window on your screen with the list of quests in it. The Log (or Quest Log) is self explanatory.
![2016-08-15](https://cloud.githubusercontent.com/assets/8658862/17890665/72ed6d86-6905-11e6-921a-263fb7b757c2.png)

**Comment by JWMcQuire** [comment] 2016-08-23 14:57
This is a baffling issue from the beginning since the quest complete sound is working for me on both my systems with Windows 10, one laptop and one refurbished desktop I am slowly upgrading.

When I did the DH starting quests to add them to the database, the quest complete sound worked fine. It has also worked fine on the pre-legion quests as well as quests I've done on my level 86 Shaman.

When Blizzard finally gets it's DDoS issues fixed, I'll log on to some of my alts in other realms to see if this issue comes up on any of them.

**Comment by Rythal** [comment] 2016-08-23 15:00
I have noticed some cases where I did not get the sound, but I also did not get the message in chat either so the quest had not been recognized as completed.... but it was rare, and the ones which did show completed made the sound, I never had a case the sound didn't play if Carbonite knew the quest was done.

**Comment by JWMcQuire** [comment] 2016-08-24 01:57
Ok, while adding the last three pre-Legion quests to the database, I didn't get the quest complete sound. 

So it is highly possible in all my stubbornness, that I have been so used to hearing the quest complete sound that I didn't notice when it wasn't working. So with apologies to those struggling with this, I'll try to pay closer attention so I can see when and where the sound doesn't pop-up. I wouldn't know how to fix it, but at least I may be able to see if it is specific to certain quests or areas and post what I find if that will help Mike fix this.

**Comment by DaveJ61** [comment] 2016-08-24 02:34
Hi. Strangely enough, this morning it wasn't working at all and despite actually doing nothing at all, this evening everything appears to be working every time. However, I have had this before and maybe the next occasion it isn't working at all. At first I thought blizzard had sneaked in a minor patch under the radar. I'll keep checking and as usual post my findings back on here.

**Comment by JWMcQuire** [comment] 2016-08-24 03:15
Yes, it does appear now that I am paying closer attention that it works or not randomly.

**Comment by DaveJ61** [comment] 2016-08-24 12:02
Aa I suspected, since logging on this morning where everything was working fine, it is now not working at all. It doesn't seem to matter whether the quest you have picked up is this session or a previous one, it still failed to do the "Quest complete".

**Comment by jeffy162** [comment] 2016-08-24 14:19
Well, the "Quest Complete" sound was working last night, for me, after installing the latest Master of Carbonite. If it continues to work today............ Now, though, I seem to have another problem.
![carb-chat debug message](https://cloud.githubusercontent.com/assets/8658862/17933786/63e6351e-69e3-11e6-982f-dba21d22de01.png)
This picture says it all. No errors show up or anything like that, just this message. This happened when I took a flight path from The Speed Barge in Thousand Needles to Camp Mojachi (spelling?) in Ferelas. Happened on a level 41 Orc Rogue.

**Comment by mikepauer** [comment] 2016-08-24 14:29
It's part of my debugging trying to find the cause... not surprised you saw it on a flightpath as it usually happens anytime your in an unknown area like over water...

**Comment by jeffy162** [comment] 2016-08-24 15:30
Ahhh. Thank you for explaining that.

**Comment by mikepauer** [comment] 2016-08-26 17:12
I just ran 11 toons through the 3 quests for dalaran, and had same result every time :( this is really frustrating... 
Quest 1) No sound, since it's complete as soon as you get it.. blizzard quest log confirms it showing complete ready for turning
Quest 2) soon as 4th anonamly is done, chat says Quest Complete, Sound plays.
Quest 3) soon as alodai finishes talking, chat says Quest Complete, Sound plays.

**Comment by DaveJ61** [comment] 2016-08-26 20:39
Mine isn't working at all at the moment. After hearthing back to Zangamarsh from Shattrath, it did actually say the "quest complete" on a couple of quests that I completed a long time ago and havent turned in yet. It has done this on numerous occasions. Otherwise I get nothing at all. Glad to know I'm not the only one.

**Comment by DaveJ61** [comment] 2016-08-27 14:39
Had a couple of instances where the "Quest Complete" sounded off after using a portal to Orgrimmar and then after using the Zep from Org to UC.
![carb8](https://cloud.githubusercontent.com/assets/1816367/18028059/1b21fad0-6c6c-11e6-8e16-508b4f4080d4.JPG)
![carb9](https://cloud.githubusercontent.com/assets/1816367/18028060/1fe7a65a-6c6c-11e6-8d66-f27365a01a99.JPG)
I then went back to Arathi Highlands to farm some cooking mats and after I had completed the quest, it actually said "Quest complete". This only happened once.

**Comment by SteveEbey73742** [comment] 2016-09-30 19:16
This issue seems to be fixed.  Can we close it?

**Comment by IrcDirk** [comment] 2016-09-30 19:48
More people should confirm if this fixed.

**Comment by Kabulla** [comment] 2016-10-01 12:06
I still have it but I am not sure if it is exactly the same issue.
I seem to have the phenomenon whenever I change zones or zip in and out of instances.
During instances it also spams the quest-progress repeatedly...
Could be related to other addons also, as I am generally running tons of them.
So this might be something that needs a separate adressing.
Won't be in front of my machine before late, tomorrow. So I can't answer details until then, if needed and/or wanted...

**Comment by Kabulla** [comment] 2016-10-01 12:08
Additional remark:
I am relating to the "belated quest complete", I don't experience the "missing sound" part of the original request...

**Comment by DaveJ61** [comment] 2016-10-03 11:09
I think this is now working for me. I need to test this more thoroughly but can't until later today.

**Comment by DaveJ61** [comment] 2016-10-04 08:04
This appears to be working for me now.

**Closed** 2016-10-04 08:04 UTC
Labels: fixed please confirm
