### ISSUE TITLE
Carbonite.Quests attempted to call a forbidden function  (UseWorldMapActionButtonSpellOnQuest())

### ISSUE THREAD

**Issue by ChaoticWonder** [mikepauer/Carbonite#646] opened 2017-05-05 04:56 UTC
Error comes up when trying to use Warlock class hall ability _Unleash Infernal_ on World Map.

After getting this I tried with only Carbonite enabled and got the same error.  If I disable Carbonite.Quests the ability works fine.  Latest pull from GitHub as of May 3.

Date: 2017-05-05 00:36:31
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 1
Message: Error: AddOn Carbonite.Quests attempted to call a forbidden function 
(UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:2020:
      ..\FrameXML\WorldMapFrame.lua:2016
   [C]: ?
Locals:
None
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  WowheadLooter, v60014
  AnnoyingPopupRemover, v3.1-release
  AskMrRobot, v50
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BodyguardHealth, vv2.5.1
  CanIMogIt, v7.2.0.02
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  ClassMods, vv1.32
  Configator, v5.1.DEV.406(/embedded)
  CrapAway, v
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  FBBroker, v1.31
  FBMergeDatabase, v1.4w
  FBOutfitDisplayFrame, v1.7.13
  FBTrackingFrame, v1.7.11
  FishingBuddy, v1.7.13a
  GTFO, v4.42.12
  HandyNotes, vv1.4.13
  HandyNotesAzerothsTopTunes, vv1.2.1
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesDungeonLocations, v1.17
  HandyNotesFieldPhotographer, v7.1.0.0
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.4.4
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.17
  HandyNotesTimelessTreasures, v1.0.7
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  LibSharedMedia30, v3.0-97
  MasterPlanA, vA
  NeedPrimalSpirits, v1.2
  NomiCakes, v7.2.0.1
  Pawn, v2.2.4
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Simulationcraft, v1.7.0
  Skada, v1.6.6
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TabardAddict, v2.36
  TipHelper, v5.12.DEV.405(/embedded)
  WeakAuras, v2.4.1
  WorldQuestGroupFinder, v0.24.3
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=d5c)

**Comment by fdellwing** [comment] 2017-05-05 06:58
Marked as duplicate of #644

**Closed** 2017-05-05 07:17 UTC
